[package]
name = "brackets-macros"
version = "0.0.0"
description = "Macros for the brackets crate."
license-file = "LICENSE.txt"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.63", features = ["full"] }
quote = "1.0.36"
